### ISSUE TITLE
Зач скопировал?

### ISSUE THREAD

**Issue by glutesha** [EternalB-1/discord-crasher#1]

**Comment by nintendoboy5000** [comment]
))))

**Comment by glutesha** [comment]
Не ну аче

**Comment by EternalB-1** [comment]
Я просто собираю классные репозитории, но также указываю откуда они скопированы (:

> Не ну аче

**Comment by glutesha** [comment]
Я так и думал, прост еще нинтендо бомбил сильно, лан, спс за ответ
